server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:5432/postgres
    url: postgres://mprckkvbhhyuam:d5a1a20fb004afe1d72936d4d7c7db460f54bad63657b278febefd764605735f@ec2-50-17-255-120.compute-1.amazonaws.com:5432/d97f5jag4k1h4n
    #username: postgres
    username: mprckkvbhhyuam
    #password: 123456
    password: d5a1a20fb004afe1d72936d4d7c7db460f54bad63657b278febefd764605735f
    url: jdbc:postgresql://localhost:5432/postgres    
    username: postgres    
    password: 123456
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander / Backend
